name: Nightly build of pip-package

on:
  workflow_dispatch:
  schedule:
  - cron: '30 3 * * *'

permissions:
  contents: read

jobs:
  ubuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run package creation
      run: |
        python -m pip install --user --upgrade build
        python -m build
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        name: CAD_to_OpenMC
        path: dist
        retention-days: 2
        overwrite: true

